apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: router-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: test-cfs
  volumeMode: Filesystem
  volumeName: router-pv