apiVersion: v1
kind: PersistentVolume
metadata:
  name: router-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: com.tencent.cloud.csi.cfs
    volumeAttributes:
      fsid: n4bym5fk
      host: 10.0.0.92
      path: /
      vers: "3"
    volumeHandle: router-pv
  persistentVolumeReclaimPolicy: Retain
  storageClassName: test-cfs
  volumeMode: Filesystem
