plugins:
  cos.jwt_plugin:
    enable: true
include_subgraph_errors:
  all: true  # 这将包含所有子图的错误
  # 或者，如果您只想包含特定子图的错误：
  # subgraphs: 
  #   - user

supergraph:
  listen: 0.0.0.0:4666

server:
  cors:
    allow_credentials: true
    allow_headers:
      - Content-Type
      - Authorization
    methods:
      - POST
      - GET
      - OPTIONS

headers:
  all:
    request:
      - propagate:
          matching: .*
      - insert:
          name: X-User-Id
          from_context: UserId