// Code generated by Kitex v0.10.3. DO NOT EDIT.

package securityservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	token "github.com/light-speak/lightdoor/security/kitex_gen/token"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetSecurityUserId(ctx context.Context, Req *token.TokenRequest, callOptions ...callopt.Option) (r *token.TokenResponse, err error)
	GetSecurityToken(ctx context.Context, Req *token.UserIdRequest, callOptions ...callopt.Option) (r *token.TokenResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kSecurityServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSecurityServiceClient struct {
	*kClient
}

func (p *kSecurityServiceClient) GetSecurityUserId(ctx context.Context, Req *token.TokenRequest, callOptions ...callopt.Option) (r *token.TokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSecurityUserId(ctx, Req)
}

func (p *kSecurityServiceClient) GetSecurityToken(ctx context.Context, Req *token.UserIdRequest, callOptions ...callopt.Option) (r *token.TokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSecurityToken(ctx, Req)
}
